# Site
repository: huiyicao/huiyicao.github.io
favicon: images/favicon.ico

# Personal info
name: Huiyi Cao
title: Ph.D. Candicate
email: caoh14@mcmaster.ca
website: https://huiyicao.github.io/

# Social links
# twitter_username: facespics
github_username:  huiyicao
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: huiyi-cao
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Huiyi.  

  I am most skilled in: <mark>Optimization</mark> and <mark>Eating</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Bla

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
